version: '3'
services:
  redis:
    restart: always
    image: redis:buster
    container_name: redis_jeff
    command: redis-server --port 6378 --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6378:6378"
    networks:
      - connect

  jefferson:
    container_name: jefferson
    restart: always
    build:
      context: .
    depends_on:
      - redis
    networks:
      - connect
  
  scheduler:
    container_name: scheduler_jeff
    restart: always
    build:
      context: ./scheduler
    depends_on:
      - redis
    networks:
      - connect

networks:
  connect:
    driver: bridge

volumes:
  redis-data:
