# This is a basic workflow to help you get started with Actions

name: test_data_eng

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Getting the ECR repos
        shell: bash
        run: |
          array=()
          for file in images/test_2/dockerfile images/db_acess/dockerfile images/test_2/requirements.txt ;do

              if [[ $file =~ ^images/* ]];then
                  echo $file
                  IMAGE_DIR=$(cut -d '/' -f 1 <<< $file)
                  array+=($(cut -d '/' -f 2 <<< $file))
              fi
          done

          echo ""
          echo "IMAGE_DIR=$IMAGE_DIR"


          echo ""
          echo "#########################"
          echo "ECR_REPOS WITHOUT CLEANING"
          echo ${array[@]}

          echo ""
          echo "##################################"
          echo "SORTING AND ELIMINATING DUPLICATES"
          sorted_array=()
          sorted_array=( `for i in ${array[@]};do echo $i; done | sort -u` )

          echo ${sorted_array[@]}
              