# This is a basic workflow to help you get started with Actions

name: engineering_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'app/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ECR_REPOS_AND_TAGS: [db_acess@1,test_2@2]
    steps:
      - name: "Checking how data we get back is structured"
        shell: bash
        run: |
          echo "REPO:"
          echo "${{ matrix.ECR_REPOS_AND_TAGS }}"
      