# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: SSH login and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.PRIVATE_LOGIN_TOKEN }}
        port: 22
        script: |
          if [ $( docker ps -a -f "ancestor=jefferson" | wc -l ) -gt 0 ]; then
              docker stop $( docker ps -aq -f "ancestor=jefferson" )
              docker rm $( docker ps -aq -f "ancestor=jefferson" )
          fi

          cd /home/pi/apps/jeff-discord
          git pull
          docker build -t jefferson .
          docker run -d --restart always jefferson

    